/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddCertificateRequest model module.
 * @module com.alterian.auth.model/AddCertificateRequest
 * @version 6.35.0
 */
class AddCertificateRequest {
    /**
     * Constructs a new <code>AddCertificateRequest</code>.
     * @alias module:com.alterian.auth.model/AddCertificateRequest
     */
    constructor() { 
        
        AddCertificateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddCertificateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/AddCertificateRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/AddCertificateRequest} The populated <code>AddCertificateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddCertificateRequest();

            if (data.hasOwnProperty('System')) {
                obj['System'] = ApiClient.convertToType(data['System'], 'Boolean');
            }
            if (data.hasOwnProperty('Thumbprint')) {
                obj['Thumbprint'] = ApiClient.convertToType(data['Thumbprint'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddCertificateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddCertificateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Thumbprint'] && !(typeof data['Thumbprint'] === 'string' || data['Thumbprint'] instanceof String)) {
            throw new Error("Expected the field `Thumbprint` to be a primitive type in the JSON string but got " + data['Thumbprint']);
        }

        return true;
    }


}



/**
 * Is this a system certificate
 * @member {Boolean} System
 */
AddCertificateRequest.prototype['System'] = undefined;

/**
 * Certificate thumbprint.  This field is required.
 * @member {String} Thumbprint
 */
AddCertificateRequest.prototype['Thumbprint'] = undefined;






export default AddCertificateRequest;

