/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Issuer from './Issuer';

/**
 * The AddIssuerRequest model module.
 * @module com.alterian.auth.model/AddIssuerRequest
 * @version 6.35.0
 */
class AddIssuerRequest {
    /**
     * Constructs a new <code>AddIssuerRequest</code>.
     * @alias module:com.alterian.auth.model/AddIssuerRequest
     */
    constructor() { 
        
        AddIssuerRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddIssuerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/AddIssuerRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/AddIssuerRequest} The populated <code>AddIssuerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddIssuerRequest();

            if (data.hasOwnProperty('Issuer')) {
                obj['Issuer'] = Issuer.constructFromObject(data['Issuer']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddIssuerRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddIssuerRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Issuer`
        if (data['Issuer']) { // data not null
          Issuer.validateJSON(data['Issuer']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.auth.model/Issuer} Issuer
 */
AddIssuerRequest.prototype['Issuer'] = undefined;






export default AddIssuerRequest;

