/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoginInfo from './LoginInfo';

/**
 * The AddLoginRequest model module.
 * @module com.alterian.auth.model/AddLoginRequest
 * @version 6.35.0
 */
class AddLoginRequest {
    /**
     * Constructs a new <code>AddLoginRequest</code>.
     * @alias module:com.alterian.auth.model/AddLoginRequest
     */
    constructor() { 
        
        AddLoginRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/AddLoginRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/AddLoginRequest} The populated <code>AddLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddLoginRequest();

            if (data.hasOwnProperty('Login')) {
                obj['Login'] = LoginInfo.constructFromObject(data['Login']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddLoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddLoginRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Login`
        if (data['Login']) { // data not null
          LoginInfo.validateJSON(data['Login']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.auth.model/LoginInfo} Login
 */
AddLoginRequest.prototype['Login'] = undefined;






export default AddLoginRequest;

