/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Setting from './Setting';

/**
 * The AddSettingRequest model module.
 * @module com.alterian.auth.model/AddSettingRequest
 * @version 6.35.0
 */
class AddSettingRequest {
    /**
     * Constructs a new <code>AddSettingRequest</code>.
     * @alias module:com.alterian.auth.model/AddSettingRequest
     */
    constructor() { 
        
        AddSettingRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddSettingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/AddSettingRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/AddSettingRequest} The populated <code>AddSettingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddSettingRequest();

            if (data.hasOwnProperty('Setting')) {
                obj['Setting'] = Setting.constructFromObject(data['Setting']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddSettingRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddSettingRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Setting`
        if (data['Setting']) { // data not null
          Setting.validateJSON(data['Setting']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.auth.model/Setting} Setting
 */
AddSettingRequest.prototype['Setting'] = undefined;






export default AddSettingRequest;

