/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationLoginRequest model module.
 * @module com.alterian.auth.model/ApplicationLoginRequest
 * @version 6.35.0
 */
class ApplicationLoginRequest {
    /**
     * Constructs a new <code>ApplicationLoginRequest</code>.
     * @alias module:com.alterian.auth.model/ApplicationLoginRequest
     */
    constructor() { 
        
        ApplicationLoginRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/ApplicationLoginRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/ApplicationLoginRequest} The populated <code>ApplicationLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationLoginRequest();

            if (data.hasOwnProperty('SiteId')) {
                obj['SiteId'] = ApiClient.convertToType(data['SiteId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationLoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationLoginRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Id of the application to which you wish to obtain an access token.  The list of available site ids is returned from either @see(FormsAuthentication) or @see(SAMLAuthentication)
 * @member {Number} SiteId
 */
ApplicationLoginRequest.prototype['SiteId'] = undefined;






export default ApplicationLoginRequest;

