/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Applications.
* @enum {}
* @readonly
*/
export default class Applications {
    
        /**
         * value: 0
         * @const
         */
        "All" = 0;

    
        /**
         * value: 1
         * @const
         */
        "Alchemy" = 1;

    
        /**
         * value: 2
         * @const
         */
        "DynamicMessenger" = 2;

    
        /**
         * value: 3
         * @const
         */
        "Management" = 3;

    
        /**
         * value: 4
         * @const
         */
        "AlchemyManagement" = 4;

    
        /**
         * value: 5
         * @const
         */
        "Tridion" = 5;

    
        /**
         * value: 6
         * @const
         */
        "RERE" = 6;

    
        /**
         * value: 7
         * @const
         */
        "PowerBI" = 7;

    

    /**
    * Returns a <code>Applications</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.alterian.auth.model/Applications} The enum <code>Applications</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

