/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteIssuerRequest model module.
 * @module com.alterian.auth.model/DeleteIssuerRequest
 * @version 6.35.0
 */
class DeleteIssuerRequest {
    /**
     * Constructs a new <code>DeleteIssuerRequest</code>.
     * @alias module:com.alterian.auth.model/DeleteIssuerRequest
     */
    constructor() { 
        
        DeleteIssuerRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteIssuerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/DeleteIssuerRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/DeleteIssuerRequest} The populated <code>DeleteIssuerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteIssuerRequest();

            if (data.hasOwnProperty('IssuerId')) {
                obj['IssuerId'] = ApiClient.convertToType(data['IssuerId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteIssuerRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteIssuerRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The Id of the issuer to be deleted.
 * @member {Number} IssuerId
 */
DeleteIssuerRequest.prototype['IssuerId'] = undefined;






export default DeleteIssuerRequest;

