/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APICursor from './APICursor';

/**
 * The GetSettingsValuesRequest model module.
 * @module com.alterian.auth.model/GetSettingsValuesRequest
 * @version 6.35.0
 */
class GetSettingsValuesRequest {
    /**
     * Constructs a new <code>GetSettingsValuesRequest</code>.
     * @alias module:com.alterian.auth.model/GetSettingsValuesRequest
     */
    constructor() { 
        
        GetSettingsValuesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSettingsValuesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/GetSettingsValuesRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/GetSettingsValuesRequest} The populated <code>GetSettingsValuesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSettingsValuesRequest();

            if (data.hasOwnProperty('Cursor')) {
                obj['Cursor'] = APICursor.constructFromObject(data['Cursor']);
            }
            if (data.hasOwnProperty('IssuerId')) {
                obj['IssuerId'] = ApiClient.convertToType(data['IssuerId'], 'Number');
            }
            if (data.hasOwnProperty('LoginId')) {
                obj['LoginId'] = ApiClient.convertToType(data['LoginId'], 'String');
            }
            if (data.hasOwnProperty('SettingIds')) {
                obj['SettingIds'] = ApiClient.convertToType(data['SettingIds'], ['Number']);
            }
            if (data.hasOwnProperty('SiteId')) {
                obj['SiteId'] = ApiClient.convertToType(data['SiteId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSettingsValuesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSettingsValuesRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Cursor`
        if (data['Cursor']) { // data not null
          APICursor.validateJSON(data['Cursor']);
        }
        // ensure the json data is a string
        if (data['LoginId'] && !(typeof data['LoginId'] === 'string' || data['LoginId'] instanceof String)) {
            throw new Error("Expected the field `LoginId` to be a primitive type in the JSON string but got " + data['LoginId']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['SettingIds'])) {
            throw new Error("Expected the field `SettingIds` to be an array in the JSON data but got " + data['SettingIds']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.auth.model/APICursor} Cursor
 */
GetSettingsValuesRequest.prototype['Cursor'] = undefined;

/**
 * Issuer Id the Setting Applies to
 * @member {Number} IssuerId
 */
GetSettingsValuesRequest.prototype['IssuerId'] = undefined;

/**
 * Login Id the Setting Applies to
 * @member {String} LoginId
 */
GetSettingsValuesRequest.prototype['LoginId'] = undefined;

/**
 * List of setting Ids
 * @member {Array.<Number>} SettingIds
 */
GetSettingsValuesRequest.prototype['SettingIds'] = undefined;

/**
 * Site Id the Setting Applies to
 * @member {Number} SiteId
 */
GetSettingsValuesRequest.prototype['SiteId'] = undefined;






export default GetSettingsValuesRequest;

