/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSettingRequest model module.
 * @module com.alterian.auth.model/GetSettingRequest
 * @version 6.35.0
 */
class GetSettingRequest {
    /**
     * Constructs a new <code>GetSettingRequest</code>.
     * @alias module:com.alterian.auth.model/GetSettingRequest
     */
    constructor() { 
        
        GetSettingRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSettingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/GetSettingRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/GetSettingRequest} The populated <code>GetSettingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSettingRequest();

            if (data.hasOwnProperty('SettingId')) {
                obj['SettingId'] = ApiClient.convertToType(data['SettingId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSettingRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSettingRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The Id of a valid Setting to retrieve
 * @member {Number} SettingId
 */
GetSettingRequest.prototype['SettingId'] = undefined;






export default GetSettingRequest;

