/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APICursor from './APICursor';
import SettingAppliesTo from './SettingAppliesTo';

/**
 * The GetSettingsRequest model module.
 * @module com.alterian.auth.model/GetSettingsRequest
 * @version 6.35.0
 */
class GetSettingsRequest {
    /**
     * Constructs a new <code>GetSettingsRequest</code>.
     * @alias module:com.alterian.auth.model/GetSettingsRequest
     */
    constructor() { 
        
        GetSettingsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSettingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/GetSettingsRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/GetSettingsRequest} The populated <code>GetSettingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSettingsRequest();

            if (data.hasOwnProperty('AppliesTo')) {
                obj['AppliesTo'] = SettingAppliesTo.constructFromObject(data['AppliesTo']);
            }
            if (data.hasOwnProperty('Cursor')) {
                obj['Cursor'] = APICursor.constructFromObject(data['Cursor']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSettingsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSettingsRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Cursor`
        if (data['Cursor']) { // data not null
          APICursor.validateJSON(data['Cursor']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.auth.model/SettingAppliesTo} AppliesTo
 */
GetSettingsRequest.prototype['AppliesTo'] = undefined;

/**
 * @member {module:com.alterian.auth.model/APICursor} Cursor
 */
GetSettingsRequest.prototype['Cursor'] = undefined;






export default GetSettingsRequest;

