/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HostDetails model module.
 * @module com.alterian.auth.model/HostDetails
 * @version 6.35.0
 */
class HostDetails {
    /**
     * Constructs a new <code>HostDetails</code>.
     * 
     * @alias module:com.alterian.auth.model/HostDetails
     */
    constructor() { 
        
        HostDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HostDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/HostDetails} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/HostDetails} The populated <code>HostDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HostDetails();

            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('isHTTPS')) {
                obj['isHTTPS'] = ApiClient.convertToType(data['isHTTPS'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HostDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HostDetails</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }

        return true;
    }


}



/**
 * This is the name of the website in the IMS installation which is running the webserver.             The Host value is used to control access to this Tridion site, and by default will allow access to every user in this host.
 * @member {String} host
 */
HostDetails.prototype['host'] = undefined;

/**
 * This is a flag to say whether the Tridion site is available in an HTTPS installation of IMS.              If your IMS installation is using HTTPS then set this to 1, otherwise leave it as 0.
 * @member {Boolean} isHTTPS
 */
HostDetails.prototype['isHTTPS'] = undefined;






export default HostDetails;

