/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Issuer model module.
 * @module com.alterian.auth.model/Issuer
 * @version 6.35.0
 */
class Issuer {
    /**
     * Constructs a new <code>Issuer</code>.
     * Issuer of Certificate for single sign on
     * @alias module:com.alterian.auth.model/Issuer
     */
    constructor() { 
        
        Issuer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Issuer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/Issuer} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/Issuer} The populated <code>Issuer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Issuer();

            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'Number');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('CertificateID')) {
                obj['CertificateID'] = ApiClient.convertToType(data['CertificateID'], 'Number');
            }
            if (data.hasOwnProperty('Settings')) {
                obj['Settings'] = ApiClient.convertToType(data['Settings'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Issuer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Issuer</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['Settings'])) {
            throw new Error("Expected the field `Settings` to be an array in the JSON data but got " + data['Settings']);
        }

        return true;
    }


}



/**
 * Id of the Issuer
 * @member {Number} ID
 */
Issuer.prototype['ID'] = undefined;

/**
 * Name of the Issuer
 * @member {String} Name
 */
Issuer.prototype['Name'] = undefined;

/**
 * Id of the associated certificate
 * @member {Number} CertificateID
 */
Issuer.prototype['CertificateID'] = undefined;

/**
 * Collection of settings which this issuer uses as assertions for incoming SAML authentication requests
 * @member {Array.<Number>} Settings
 */
Issuer.prototype['Settings'] = undefined;






export default Issuer;

