/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SAMLAuthenticationRequest model module.
 * @module com.alterian.auth.model/SAMLAuthenticationRequest
 * @version 6.35.0
 */
class SAMLAuthenticationRequest {
    /**
     * Constructs a new <code>SAMLAuthenticationRequest</code>.
     * @alias module:com.alterian.auth.model/SAMLAuthenticationRequest
     */
    constructor() { 
        
        SAMLAuthenticationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SAMLAuthenticationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/SAMLAuthenticationRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/SAMLAuthenticationRequest} The populated <code>SAMLAuthenticationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SAMLAuthenticationRequest();

            if (data.hasOwnProperty('SAMLResponse')) {
                obj['SAMLResponse'] = ApiClient.convertToType(data['SAMLResponse'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SAMLAuthenticationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SAMLAuthenticationRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['SAMLResponse'] && !(typeof data['SAMLResponse'] === 'string' || data['SAMLResponse'] instanceof String)) {
            throw new Error("Expected the field `SAMLResponse` to be a primitive type in the JSON string but got " + data['SAMLResponse']);
        }

        return true;
    }


}



/**
 * Properly signed and formatted SAMLResponse.
 * @member {String} SAMLResponse
 */
SAMLAuthenticationRequest.prototype['SAMLResponse'] = undefined;






export default SAMLAuthenticationRequest;

