/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SettingValue from './SettingValue';

/**
 * The UpdateLoginExRequest model module.
 * @module com.alterian.auth.model/UpdateLoginExRequest
 * @version 6.35.0
 */
class UpdateLoginExRequest {
    /**
     * Constructs a new <code>UpdateLoginExRequest</code>.
     * @alias module:com.alterian.auth.model/UpdateLoginExRequest
     */
    constructor() { 
        
        UpdateLoginExRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateLoginExRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/UpdateLoginExRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/UpdateLoginExRequest} The populated <code>UpdateLoginExRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateLoginExRequest();

            if (data.hasOwnProperty('ExternalAuthentication')) {
                obj['ExternalAuthentication'] = ApiClient.convertToType(data['ExternalAuthentication'], 'Boolean');
            }
            if (data.hasOwnProperty('LoginId')) {
                obj['LoginId'] = ApiClient.convertToType(data['LoginId'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('NewPassword')) {
                obj['NewPassword'] = ApiClient.convertToType(data['NewPassword'], 'String');
            }
            if (data.hasOwnProperty('Settings')) {
                obj['Settings'] = ApiClient.convertToType(data['Settings'], [SettingValue]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateLoginExRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateLoginExRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['LoginId'] && !(typeof data['LoginId'] === 'string' || data['LoginId'] instanceof String)) {
            throw new Error("Expected the field `LoginId` to be a primitive type in the JSON string but got " + data['LoginId']);
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['NewPassword'] && !(typeof data['NewPassword'] === 'string' || data['NewPassword'] instanceof String)) {
            throw new Error("Expected the field `NewPassword` to be a primitive type in the JSON string but got " + data['NewPassword']);
        }
        if (data['Settings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Settings'])) {
                throw new Error("Expected the field `Settings` to be an array in the JSON data but got " + data['Settings']);
            }
            // validate the optional field `Settings` (array)
            for (const item of data['Settings']) {
                SettingValue.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Should this login be exteral authenticated
 * @member {Boolean} ExternalAuthentication
 */
UpdateLoginExRequest.prototype['ExternalAuthentication'] = undefined;

/**
 * Id of the login
 * @member {String} LoginId
 */
UpdateLoginExRequest.prototype['LoginId'] = undefined;

/**
 * Name of the login
 * @member {String} Name
 */
UpdateLoginExRequest.prototype['Name'] = undefined;

/**
 * If you want to reset the password, provide it here.  If ExternalAuth is true, this property is ignored.
 * @member {String} NewPassword
 */
UpdateLoginExRequest.prototype['NewPassword'] = undefined;

/**
 * Settings to apply to the login
 * @member {Array.<module:com.alterian.auth.model/SettingValue>} Settings
 */
UpdateLoginExRequest.prototype['Settings'] = undefined;






export default UpdateLoginExRequest;

