/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateCertificateRequest model module.
 * @module com.alterian.auth.model/UpdateCertificateRequest
 * @version 6.35.0
 */
class UpdateCertificateRequest {
    /**
     * Constructs a new <code>UpdateCertificateRequest</code>.
     * @alias module:com.alterian.auth.model/UpdateCertificateRequest
     */
    constructor() { 
        
        UpdateCertificateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateCertificateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.auth.model/UpdateCertificateRequest} obj Optional instance to populate.
     * @return {module:com.alterian.auth.model/UpdateCertificateRequest} The populated <code>UpdateCertificateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateCertificateRequest();

            if (data.hasOwnProperty('CertificateId')) {
                obj['CertificateId'] = ApiClient.convertToType(data['CertificateId'], 'Number');
            }
            if (data.hasOwnProperty('Thumbprint')) {
                obj['Thumbprint'] = ApiClient.convertToType(data['Thumbprint'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateCertificateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateCertificateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Thumbprint'] && !(typeof data['Thumbprint'] === 'string' || data['Thumbprint'] instanceof String)) {
            throw new Error("Expected the field `Thumbprint` to be a primitive type in the JSON string but got " + data['Thumbprint']);
        }

        return true;
    }


}



/**
 * Id of the certificate to update
 * @member {Number} CertificateId
 */
UpdateCertificateRequest.prototype['CertificateId'] = undefined;

/**
 * Certificate thumbprint.  If this is a system token, changes to this property are ignored.  If you attempt to make a change, it will be disregarded.
 * @member {String} Thumbprint
 */
UpdateCertificateRequest.prototype['Thumbprint'] = undefined;






export default UpdateCertificateRequest;

