/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthenticationApi);
  }
}(this, function(expect, AuthenticationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthenticationApi.AuthenticationResults();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthenticationResults', function() {
    it('should create an instance of AuthenticationResults', function() {
      // uncomment below and update the code to test AuthenticationResults
      //var instance = new AuthenticationApi.AuthenticationResults();
      //expect(instance).to.be.a(AuthenticationApi.AuthenticationResults);
    });

    it('should have the property token (base name: "Token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new AuthenticationApi.AuthenticationResults();
      //expect(instance).to.be();
    });

    it('should have the property loginID (base name: "LoginID")', function() {
      // uncomment below and update the code to test the property loginID
      //var instance = new AuthenticationApi.AuthenticationResults();
      //expect(instance).to.be();
    });

    it('should have the property sites (base name: "Sites")', function() {
      // uncomment below and update the code to test the property sites
      //var instance = new AuthenticationApi.AuthenticationResults();
      //expect(instance).to.be();
    });

    it('should have the property passwordExpired (base name: "PasswordExpired")', function() {
      // uncomment below and update the code to test the property passwordExpired
      //var instance = new AuthenticationApi.AuthenticationResults();
      //expect(instance).to.be();
    });

  });

}));
