/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthenticationApi);
  }
}(this, function(expect, AuthenticationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthenticationApi.PasswordComplexityRules();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PasswordComplexityRules', function() {
    it('should create an instance of PasswordComplexityRules', function() {
      // uncomment below and update the code to test PasswordComplexityRules
      //var instance = new AuthenticationApi.PasswordComplexityRules();
      //expect(instance).to.be.a(AuthenticationApi.PasswordComplexityRules);
    });

    it('should have the property minimumLength (base name: "MinimumLength")', function() {
      // uncomment below and update the code to test the property minimumLength
      //var instance = new AuthenticationApi.PasswordComplexityRules();
      //expect(instance).to.be();
    });

    it('should have the property numChars (base name: "NumChars")', function() {
      // uncomment below and update the code to test the property numChars
      //var instance = new AuthenticationApi.PasswordComplexityRules();
      //expect(instance).to.be();
    });

    it('should have the property numNumeric (base name: "NumNumeric")', function() {
      // uncomment below and update the code to test the property numNumeric
      //var instance = new AuthenticationApi.PasswordComplexityRules();
      //expect(instance).to.be();
    });

    it('should have the property numSpecial (base name: "NumSpecial")', function() {
      // uncomment below and update the code to test the property numSpecial
      //var instance = new AuthenticationApi.PasswordComplexityRules();
      //expect(instance).to.be();
    });

    it('should have the property requireMixedCase (base name: "RequireMixedCase")', function() {
      // uncomment below and update the code to test the property requireMixedCase
      //var instance = new AuthenticationApi.PasswordComplexityRules();
      //expect(instance).to.be();
    });

    it('should have the property passwordReuse (base name: "PasswordReuse")', function() {
      // uncomment below and update the code to test the property passwordReuse
      //var instance = new AuthenticationApi.PasswordComplexityRules();
      //expect(instance).to.be();
    });

  });

}));
