/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthenticationApi);
  }
}(this, function(expect, AuthenticationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthenticationApi.AuthenticationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthenticationApi', function() {
    describe('applicationLogin', function() {
      it('should call applicationLogin successfully', function(done) {
        //uncomment below and update the code to test applicationLogin
        //instance.applicationLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('formsAuthentication', function() {
      it('should call formsAuthentication successfully', function(done) {
        //uncomment below and update the code to test formsAuthentication
        //instance.formsAuthentication(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIdentityUrl', function() {
      it('should call getIdentityUrl successfully', function(done) {
        //uncomment below and update the code to test getIdentityUrl
        //instance.getIdentityUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSiteDetails', function() {
      it('should call getSiteDetails successfully', function(done) {
        //uncomment below and update the code to test getSiteDetails
        //instance.getSiteDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logout', function() {
      it('should call logout successfully', function(done) {
        //uncomment below and update the code to test logout
        //instance.logout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nTLMAuthentication', function() {
      it('should call nTLMAuthentication successfully', function(done) {
        //uncomment below and update the code to test nTLMAuthentication
        //instance.nTLMAuthentication(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('openIdAuthentication', function() {
      it('should call openIdAuthentication successfully', function(done) {
        //uncomment below and update the code to test openIdAuthentication
        //instance.openIdAuthentication(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sAMLAuthentication', function() {
      it('should call sAMLAuthentication successfully', function(done) {
        //uncomment below and update the code to test sAMLAuthentication
        //instance.sAMLAuthentication(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
