/**
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthenticationApi);
  }
}(this, function(expect, AuthenticationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthenticationApi.LoginsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoginsApi', function() {
    describe('addLogin', function() {
      it('should call addLogin successfully', function(done) {
        //uncomment below and update the code to test addLogin
        //instance.addLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('disableLogin', function() {
      it('should call disableLogin successfully', function(done) {
        //uncomment below and update the code to test disableLogin
        //instance.disableLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enableLogin', function() {
      it('should call enableLogin successfully', function(done) {
        //uncomment below and update the code to test enableLogin
        //instance.enableLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentLogin', function() {
      it('should call getCurrentLogin successfully', function(done) {
        //uncomment below and update the code to test getCurrentLogin
        //instance.getCurrentLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLogin', function() {
      it('should call getLogin successfully', function(done) {
        //uncomment below and update the code to test getLogin
        //instance.getLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLogins', function() {
      it('should call getLogins successfully', function(done) {
        //uncomment below and update the code to test getLogins
        //instance.getLogins(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('renameLogin', function() {
      it('should call renameLogin successfully', function(done) {
        //uncomment below and update the code to test renameLogin
        //instance.renameLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLogin', function() {
      it('should call updateLogin successfully', function(done) {
        //uncomment below and update the code to test updateLogin
        //instance.updateLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLoginEx', function() {
      it('should call updateLoginEx successfully', function(done) {
        //uncomment below and update the code to test updateLoginEx
        //instance.updateLoginEx(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
